# Generated by Django 5.0.6 on 2024-10-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='total_time',
            field=models.PositiveIntegerField(help_text='Time spent in minutes', null=True),
        ),
    ]
